<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.tschanz.v_bro</groupId>
        <artifactId>v-bro-parent</artifactId>
        <relativePath>../pom.xml</relativePath>
        <version>0.0.1</version>
    </parent>

    <artifactId>v-bro-app</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-app-presentation</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-app-presentation-jfx</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-app-usecase</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-data-structure-domain</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-data-structure-persistence-jdbc</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-data-structure-persistence-mock</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-data-structure-persistence-xml</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-repo-domain</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-repo-persistence-jdbc</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-repo-persistence-mock</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.tschanz.v_bro</groupId>
            <artifactId>v-bro-repo-persistence-xml</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <groupId>org.apache.maven.plugins</groupId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.tschanz.v_bro.app.Main</mainClass>
                                </transformer>
                            </transformers>
                            <finalName>${project.artifactId}-${project.version}-jar-with-dependencies</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>